apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    release: baseline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: baseline
      labels:
        app: web
        release: baseline
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: "nicholasjackson/fake-service:v0.19.1"
          ports:
            - containerPort: 9090
          env:
            - name: NAME
              value: "Web (baseline)"
            - name: MESSAGE
              value: "Web (baseline)"
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10